on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

jobs:
  test_action:
    runs-on: ubuntu-latest
    name: Test KinD action
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - name: Kind Action Test
        uses: ./kind
      - name: Get Nodes
        run: kubectl get nodes
      - name: Create POD
        run: kubectl apply -f https://k8s.io/examples/pods/simple-pod.yaml
